4Catalyzer/flask-resty

flask_jsonapiview/__init__.py, flask_jsonapiview/authentication.py, flask_jsonapiview/authorization.py, flask_jsonapiview/view.py
This allows derived views to call into the authorization handler without
checking for their existence
=> Add explicit no-op auth handlers

flask_resty/view.py, tests/test_view_errors.py, tox.ini
These are due to e.g. type errors that are better handled by the schema.
=> Don't catch DataErrors

flask_resty/api.py, flask_resty/filtering.py, flask_resty/pagination.py, flask_resty/sorting.py, flask_resty/spec/__init__.py, flask_resty/spec/declaration.py, flask_resty/spec/operation.py, flask_resty/spec/plugin.py, flask_resty/spec/utils.py, flask_resty/view.py, setup.py, tests/test_swagger.py, tox.ini
with this pr is possible to use `flask_res.spec` as a plugin to [apispec](https://github.com/marshmallow-code/apispec) to generate swagger options.
Some remarks: I don’t know if the idea of subclassing `SpecDeclaration`
is a good way to do it. I tried to automate as many things as possible,
with the result that the end result might not always be correct. The
View can always subclass SpecDeclaration and correct any errors coming
from the view superclasses.
=> add apispec plugin

flask_resty/view.py, tests/test_auth.py
This changes get_item_or_404 with create_missing to check that the user is authorized to save the item (even if not committing), and raise a 404 if not.
We bypass this check when using the update path with create_missing set, as we will separately authorize saving the created item before committing.
I haven't added full test coverage for both branches of this feature yet. Let me know if this seems reasonable though.
=> Fix create missing semantics

flask_resty/__init__.py, flask_resty/pagination.py, tests/test_pagination.py, tests/test_swagger.py
It's not the more common REST cursor-based pagination strategy.
=> Rename CursorPagination to RelayCursorPagination

flask_resty/compat.py, flask_resty/testing.py
Either we remove them, or we come up with something more generic. probably we don't need them at all. eg If `actual` is not dictionary-ish enough to have `.get`, it will fail anyway
=> relax assert_value

flask_resty/view.py
This handles the case where created items are not retrievable, for whatever reason.
=> Support returning None from get_location

flask_resty/filtering.py, flask_resty/pagination.py, flask_resty/sorting.py, flask_resty/spec/operation.py, tests/test_filtering.py, tests/test_pagination.py, tests/test_sorting.py
=> Use 'query' instead of 'parameter' in source

flask_resty/filtering.py, flask_resty/pagination.py, flask_resty/sorting.py, flask_resty/spec/operation.py, tests/test_filtering.py, tests/test_pagination.py, tests/test_sorting.py
Reverts 4Catalyzer/flask-resty#127
#149 is breaking anyway so why not
=> Revert "Use 'query' instead of 'parameter' in source"

flask_resty/view.py
This avoids issues when joins are involved.
=> Set of in with_for_update

flask_resty/view.py, tests/test_auth.py
Thinking about this more, it doesn't really make sense to do `add_item` in the `create_missing` branch. If you're doing an update, you will set `will_update_item`. If not, you're not going to save the item anyway, so adding it doesn't accomplish anything.
This also makes the permission checking more straightforward. After all, it's `create_missing`, not `create_and_add_missing`.
=> Do not add in create_missing when not updating

flask_resty/view.py
This makes it easier to override the logic associated with getting the
request data w/o ovverriding the de-serializer.
=> feature: add get_raw_request_data

flask_resty/view.py
If `make_response` does not assume the content type then we can return
things that are not `application/json` without re-implementing both
`make_response` and `make_response_body`.
=> chore: move jsonify call to make_response_body

flask_resty/view.py
`session.flush` takes an optional `objects` specifying the set of objects that should be flushed. See: https://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.flush
=> Pass through objects to session.flush

setup.cfg, tests/test_filtering.py, tests/test_misc.py
=> chore: Address warnings in pytest output

.travis.yml, tox.ini
Visually align the `python` and `env` keys to
make them easier to read.
=> chore: Minor Travis config cleanup

setup.cfg
We ended up removing the warning about ``strict=False``
in marshmallow-code/marshmallow#1136, so this
config is no longer necessary.
=> chore: Remove unnecessary pytest config

.travis.yml
xenial supports all Python versions, so no need
to special-case it for Python 3.7.
=> chore: Use xenial for all builds

.travis.yml
...to speed up builds. We're already testing against
py27 and py35 anyway.
=> Drop pypy jobs

.travis.yml, tox.ini
marshmallow 3 no longer supports Python 2
https://github.com/marshmallow-code/marshmallow/issues/1120
=> fix: don't test against marshmallow 3 x Python 2

setup.py
I didn't realize v1.0.3 was cut. That explains why I had to make https://github.com/4Catalyzer/flask-resty/pull/261 to stay at 100% coverage.
=> fix: Fix Flask dependency range

tests/test_filtering.py
Don't test against marshmallow's validation error message for `Range`, as it differs between marshmallow 2 and 3.
=> test: fix tests

.travis.yml, setup.py
Use tox for running tests and dev commands
* `tox`: run all test environments
* `tox -e lint`: runs `pre-commit run --all-files`
* `tox -e watch-docs`: builds docs in "watch" mode
=> chore: remove "system" commands in favor of tox

flask_resty/fields.py, flask_resty/view.py, tests/test_args.py, tests/test_fields.py
For: https://github.com/4Catalyzer/flask-resty/issues/275
On Asana: https://app.asana.com/0/779493871603507/1126826827214118
This PR allows for comma-encoded query params, having multiple params with the same name (i.e. `foo=bar&foo=baz`), or even a mixture of both.
If we want to only support comma-encoded query params, we can change `request_args` to just get the value for the key and split the param value, and not use any of the features of MultiDicts.
=> fix: Support for comma-encoded query params

flask_resty/view.py
They're not really errors. Not server errors, anyway.
=> fix: Log handled integrity errors as warnings

flask_resty/view.py
Small doc fix: The docstring lists 201, but method returns 204 if successful.
=> Doc correct response for GenericModelView.destroy()

flask_resty/filtering.py, flask_resty/related.py, tests/test_filtering.py, tests/test_related.py
Sorry taken me a little while to submit a PR for this!
I'm happy to make any changes.
closes #336
=> feat: Implement | operator on Filtering and Related.

docs/guide.rst, flask_resty/shell.py, setup.py, tests/test_shell.py, tox.ini
Add an enhanced `flask shell` command that automatically imports SQLAlchemy models and marshmallow schemas.
Much of this is adapted from [flask-konch](https://github.com/sloria/flask-konch/blob/master/flask_konch/cli.py) and private code that we have in Butterfly.
=> feat: add shell command that auto-imports schemas and models

setup.py
Good news is that pyjwt 3 added some nice abstractions for working with jwk and jwk sets. Bad news is that adding a compatibility layer for making it work with 2 and 3 is not straightforward. we can eventually move to pyjwt 3 but I don't think we need to rush
=> pin jwt below 2

.github/workflows/main.yml
The publish step currently isn't running because tags aren't triggering builds
=> build: fix publishing in GitHub Actions

flask_resty/pagination.py, tests/test_pagination.py
Absolutely not sure this is the right way to do this. Basically we need info about totals and cursor index in order to provide paging UI that looks like 
I've no sense on the most efficient way to return this info tho. should we remove the selected columns from the query? is that safe? is it ok to rely on what SQL Alchemy generates here? should we provide hooks to customize it?
=> feat: add page info to connection meta

flask_resty/pagination.py, tests/test_pagination.py
I regret my earlier choices, and have gone ahead and added fully distinct limit and cursor arguments for forward and backwards pagination. I considered just saying "F it" and not making it backwards compatible however that would actually make it hard for use to consume this, if not coupled with graphql updates
=> feat: proper two way cursor pagination

flask_resty/shell.py, tests/test_shell.py
This just pulls out the default context formatter into a public function so that it can be appended to. This allows adding suffixes more easily.
Enables this use case
```python
from flask_resty.shell import context_formatter
def context_formatter_with_read_replica_warning(full_context: dict, **kwargs):
formatted_context = context_formatter(full_context, **kwargs)
if is_using_read_replica():
formatted_context += click.style(
"\nWARNING: Currently using a read replica. If you need to perform writes, call dangerously_allow_writes()",
bold=True,
fg="yellow",
)
return formatted_context
RESTY_SHELL_CONTEXT_FORMAT = context_formatter_with_read_replica_warning
```
BREAKING CHANGE: The signature for `RESTY_SHELL_CONTEXT_FORMAT` is now changed:
```python
def context_format(full_context: dict):
def …
```
=> feat(shell)!: make it easier to configure the context formatter

flask_resty/testing.py
Items are countable, so `fewer` is better grammatically.
=> fix: error message text

flask_resty/view.py
The order of the call to authorize whether an item can be added seems unusual. Opening for discussion.
=> fix: order of add item authorization check seems incorrect
