flask_resty/utils.py, flask_resty/view.py, tests/test_view_errors.py
=> Handle lists in formatting deserializer errors

flask_resty/fields.py, tests/test_fields.py
- This gives better edge case coverage
=> Actually override Nested for RelatedItem

flask_resty/jwt.py
=> Allow changing expected Authorization header_prefix in subclasses of JwtAuthentication

flask_resty/api.py, tests/test_misc.py
=> Allow resources with trailing slashes (DRF style)

flask_resty/view.py
=> Explicit use view model in get_item

flask_resty/spec/declaration.py, tests/test_swagger.py
=> [spec] uniquely name the body payload

flask_resty/__init__.py, flask_resty/authentication.py, flask_resty/authorization.py, tests/test_auth.py
This allows users to not extend HasAnyCredentialsAuthorization
=> Add HasCredentialsAuthorizationBase

flask_resty/filtering.py, flask_resty/pagination.py, flask_resty/related.py, flask_resty/sorting.py, flask_resty/view.py
Also stop naming things "spec"
=> Use named methods instead of __call__

flask_resty/api.py, flask_resty/authentication.py, flask_resty/context.py, flask_resty/meta.py
This is the official recommendation for libraries.
=> Use app context directly instead of flask.g

flask_resty/compat.py, flask_resty/testing.py, tests/helpers.py, tests/test_auth.py, tests/test_basic.py, tests/test_composite_id.py, tests/test_filtering.py, tests/test_jwt.py, tests/test_misc.py, tests/test_pagination.py, tests/test_ping.py, tests/test_related.py, tests/test_sorting.py, tests/test_testing.py, tests/test_view_errors.py
it was worthwile to change the tests to dogfood the testing module
=> add testing module

flask_resty/compat.py, flask_resty/testing.py, tests/test_testing.py
- Don't support sequences of unequal lengths
- Don't allow ANY to match nonexistent items
=> Make assert_value stricter

flask_resty/__init__.py, flask_resty/pagination.py, tests/test_pagination.py, tests/test_swagger.py
Useful for setting a hard limit on the response page size
=> Add max limit pagination

flask_resty/view.py
Generic item-related methods don't need to be on ModelView.
=> Move a few methods up into ApiView

flask_resty/pagination.py, flask_resty/sorting.py
Use sorting data in pagination if relevant.
=> Revamp sorting and cursor pagination

flask_resty/view.py, tests/test_swagger.py
This allows more custom filtering logic, and is more consistent with how SQL queries are normally written.
=> Sort list queries after filtering

flask_resty/api.py, tests/test_view_errors.py
Apparently I just had this sitting around. Not sure why I didn't PR this.
=> Format HTTP errors as JSON

flask_resty/pagination.py, flask_resty/sorting.py, tests/test_pagination.py
cc @itajaja
I think this is a more direct way at #169.
=> Automatically sort by ID in cursor pagination

flask_resty/__init__.py, flask_resty/related.py, flask_resty/view.py, tests/test_related.py
=> Support related IDs

flask_resty/authentication.py, flask_resty/context.py, flask_resty/meta.py, flask_resty/pagination.py, flask_resty/view.py
=> Tweak response meta functions and methods

flask_resty/view.py
=> make_response_body -> render_response_body

README.md
Closes https://github.com/4Catalyzer/flask-resty/issues/199
=> Added section on creating base Model

flask_resty/api.py, tests/test_view_errors.py
=> Don't handle RoutingExceptions

flask_resty/testing.py
Fixes https://github.com/4Catalyzer/flask-resty/issues/245
=> fix: Fix testing utils with Werkzeug v0.15.x

.travis.yml, README.md, flask_resty/compat.py, flask_resty/fields.py, flask_resty/view.py, tests/test_args.py, tests/test_fields.py, tox.ini
=> feat: Support marshmallow 3

.readthedocs.yml
https://docs.readthedocs.io/en/stable/config-file/v2.html
=> docs: add readthedocs config

.travis.yml, setup.py, tox.ini
See https://github.com/4Catalyzer/flask-resty/pull/267#issuecomment-502146533
=> chore: drop Python 3.5

docs/special_topics.rst
People have been confused about the `load_only=True, dump_only=True`.
=> docs: document filter-only fields

flask_resty/__init__.py, flask_resty/authentication.py, flask_resty/jwt.py, setup.py, tests/test_auth.py
=> feat: pull out HeaderAuthentication

flask_resty/exceptions.py
https://jsonapi.org/format/#errors
=> fix: s/details/detail for http exceptions

flask_resty/routing.py
=> fix: compatibility with werkzeug 1.0

flask_resty/view.py
=> Remove 204 response from update() docstring.

docs/guide.rst
For #329 
Documents filtering with multiple values in the guide.
=> Guide Filter handling of muliple values.

flask_resty/__init__.py, flask_resty/sorting.py, tests/test_sorting.py
it's simple, but seems to work.
=> feat: add ModelSorting

CONTRIBUTING.md
=> Rename testing extras in CONTRIBUTING.md.

flask_resty/shell.py
Fixes builds (#356 #357 currently failing) by fixing `shell` compatibility with newer SQLA versions.
I tested this manually on the latest versions of SQLAlchemy and Flask-SQLAlchemy as well as `SQLAlchemy<1.4`.
Found this solution from https://github.com/sqlalchemy/sqlalchemy/issues/6080#issuecomment-801223491
=> fix: fix compatibility with SQLAlchemy 1.4

flask_resty/view.py
This is more consistent, and compliant with the documentation
=> feat: return the updated item after update_item_raw

CONTRIBUTING.md, flask_resty/pagination.py, flask_resty/sorting.py, tests/test_pagination.py
POC for this since it wasn't so hard. It breaks the encapsulation of the base class a bit but it was sort of weird to begin.
=> feat: add backwards pagination

flask_resty/view.py
* moves some of the logic from upsert into upsert_item in ModelView
* use upsert_item in GenericModelView
=> refactor: move upsert logic up inheritance chain

flask_resty/testing.py
easy win? I don't know honestly!
=> Add assert messages?

flask_resty/pagination.py, tests/test_pagination.py
Having played with this API a bit, I can safely say that `index` should always be the index of the first item in the returned range
=> fix: make page_info index consistently the start index

flask_resty/jwt.py
The previous `pyjwt` property was internal only it looks like, so making more explicit with `__` prefix
=> chore: pyjwt is an internal implementation detail it looks like

.pre-commit-config.yaml, flask_resty/view.py, pyproject.toml, tests/test_basic.py, tests/test_composite_id.py, tests/test_misc.py, tests/test_shell.py, tests/test_view_errors.py
Not sure if this is the correct fix for #385
=> fix: location url should be relative

flask_resty/pagination.py, flask_resty/sorting.py, tests/test_pagination.py
This PR fixing issues:
1. Support paginating by NULLS in `RelayCursorPaginator`
2. Make consistent sorting by NULLS (nulls last and nulls first)
3. Deserialize "None" into None
=> fix: paginating with nulls by RelayCursorPaginator [PUFF-246]

.github/workflows/main.yml
=> chore: update actions to v3

README.md
Updates badge links from Travis CI to GitHub Actions
=> fix: update readme badge links
